[build]
  command = "npm run netlify"
  commandOrigin = "config"
  publish = "dist"
  publishOrigin = "config"

[context.production.environment]
  NODE_ENV = "development"
  PORT = "8000"
  MONGODB_PATH = "@clusterdpri.rhedrus.mongodb.net/?retryWrites=true&w=majority"
  MONGODB_USER = "bfactor041789"
  MONGODB_PASSWORD = "bfactor041789"
  JWT_SECRET = "438724730b20c2dbca9bd40e67e496d9a5ee4d1cae3d7eda50ba1f3781734f42"